package com.wincdspro.app.model.wincds.core

import com.wincdspro.app.util.Mapper
import org.junit.Assert.assertNotNull
import org.junit.Test

class ItemTest {
    @Test
    fun testDeserialize() {
        assertNotNull(Mapper.fromJson(fullItem(), Item::class.java))
    }

    fun fullItem(): String {
        return """
{
  "style": "6000-066",
  "vendor": "VIRGINIA HOUSE",
  "rn": 454,
  "rDate": "1/12/1999",
  "dept": "3",
  "vendorNo": "800",
  "desc": "40\" * 60\" CORNER COMPUTER DESK",
  "minStk": 0,
  "freight": 8,
  "gM": 48,
  "markUp": 40,
  "cost": 450,
  "landed": 486,
  "onSale": 935.5,
  "list": 1369.95,
  "comments": "",
  "available": 7,
  "onHand": 8,
  "loc1Bal": 4,
  "loc2Bal": 3,
  "loc3Bal": 0,
  "loc4Bal": 0,
  "loc5Bal": 0,
  "loc6Bal": 0,
  "loc7Bal": 0,
  "loc8Bal": 0,
  "loc9Bal": 0,
  "loc10Bal": 0,
  "loc11Bal": 0,
  "loc12Bal": 0,
  "loc13Bal": 0,
  "loc14Bal": 0,
  "loc15Bal": 0,
  "loc16Bal": 0,
  "onOrder1": 2,
  "onOrder2": 0,
  "onOrder3": 0,
  "onOrder4": 0,
  "onOrder5": 0,
  "onOrder6": 0,
  "onOrder7": 0,
  "onOrder8": 0,
  "onOrder9": 0,
  "onOrder10": 0,
  "onOrder11": 0,
  "onOrder12": 0,
  "onOrder13": 0,
  "onOrder14": 0,
  "onOrder15": 0,
  "onOrder16": 0,
  "sales1": 0,
  "sales2": 0,
  "sales3": 2,
  "sales4": 0,
  "pSales1": 0,
  "pSales2": 0,
  "pSales3": 0,
  "pSales4": 0,
  "poSold": 0,
  "gMROI": null,
  "fabric": null,
  "sku": null,
  "blank": null,
  "freightType": 0,
  "spiff": null,
  "cubes": null,
  "loc17Bal": null,
  "loc18Bal": null,
  "loc19Bal": null,
  "loc20Bal": null,
  "loc21Bal": null,
  "loc22Bal": null,
  "loc23Bal": null,
  "loc24Bal": null,
  "loc25Bal": null,
  "loc26Bal": null,
  "loc27Bal": null,
  "loc28Bal": null,
  "loc29Bal": null,
  "loc30Bal": null,
  "loc31Bal": null,
  "loc32Bal": null,
  "onOrder17": null,
  "onOrder18": null,
  "onOrder19": null,
  "onOrder20": null,
  "onOrder21": null,
  "onOrder22": null,
  "onOrder23": null,
  "onOrder24": null,
  "onOrder25": null,
  "onOrder26": null,
  "onOrder27": null,
  "onOrder28": null,
  "onOrder29": null,
  "onOrder30": null,
  "onOrder31": null,
  "onOrder32": null
}
"""
    }
}
