package com.wincdspro.app.model.wincds.core

import com.wincdspro.app.util.Mapper
import org.junit.Assert
import org.junit.Test

class SaleTest {

    @Test
    fun testDeserialize() {

        val value = fullSale()
        val obj = Mapper.Companion.fromJson(value, Sale::class.java)
        Assert.assertNotNull(obj)
    }

    private fun fullSale() = """
 {
  "leaseNo": "10348",
  "index": 302,
  "sale": 1983.26,
  "deposit": 283.26,
  "status": "O",
  "comm": "N",
  "margStart": 2090,
  "lastPay": "8/27/1999",
  "nonTaxable": null,
  "salesman": "01",
  "fldPosted": null,
  "arNo": null,
  "items": [
    {
      "marginLine": 2090,
      "saleNo": "10348",
      "quantity": 1,
      "style": "6000-066",
      "vendor": "VIRGINIA HOUSE",
      "desc": "TRIPLE DRESSER",
      "porD": "",
      "deptNo": "3",
      "vendorNo": "800",
      "commission": " ",
      "cost": 450,
      "itemFreight": 36,
      "sellPrice": 935.5,
      "salesman": "01",
      "status": "ST",
      "location": 1,
      "sellDate": "8/27/1999",
      "delDate": null,
      "rn": 454,
      "store": 1,
      "name": "CARTER",
      "shipDate": null,
      "gM": 48,
      "tele": "7402863125",
      "detail": 469,
      "mailIndex": 302,
      "sS": "",
      "delPrint": "",
      "pullPrint": null,
      "commPd": null,
      "fldPosted": null,
      "spiff": null,
      "salesSplit": null,
      "stopStart": null,
      "stopEnd": null,
      "isPackage": 0,
      "packSell": 935.5,
      "packSellGM": 48,
      "packSaleGM": 48.05,
      "transID": null
    },
    {
      "marginLine": 2091,
      "saleNo": "10348",
      "quantity": 1,
      "style": "6000-085",
      "vendor": "VIRGINIA HOUSE",
      "desc": "CHEST",
      "porD": "",
      "deptNo": "3",
      "vendorNo": "800",
      "commission": " ",
      "cost": 450,
      "itemFreight": 36,
      "sellPrice": 935.5,
      "salesman": "01",
      "status": "ST",
      "location": 1,
      "sellDate": "8/27/1999",
      "delDate": null,
      "rn": 456,
      "store": 1,
      "name": "CARTER",
      "shipDate": null,
      "gM": 48,
      "tele": "7402863125",
      "detail": 470,
      "mailIndex": 302,
      "sS": "",
      "delPrint": "",
      "pullPrint": null,
      "commPd": null,
      "fldPosted": null,
      "spiff": null,
      "salesSplit": null,
      "stopStart": null,
      "stopEnd": null,
      "isPackage": 0,
      "packSell": 935.5,
      "packSellGM": 48,
      "packSaleGM": 48.05,
      "transID": null
    },
    {
      "marginLine": 2092,
      "saleNo": "10348",
      "quantity": 0,
      "style": "SUB",
      "vendor": "",
      "desc": "Sub Total =",
      "porD": "",
      "deptNo": "3",
      "vendorNo": "800",
      "commission": " ",
      "cost": 0,
      "itemFreight": 0,
      "sellPrice": 1871,
      "salesman": "01",
      "status": "",
      "location": 0,
      "sellDate": "8/27/1999",
      "delDate": null,
      "rn": 0,
      "store": 1,
      "name": "CARTER",
      "shipDate": null,
      "gM": 0,
      "tele": "7402863125",
      "detail": null,
      "mailIndex": 302,
      "sS": null,
      "delPrint": null,
      "pullPrint": null,
      "commPd": null,
      "fldPosted": null,
      "spiff": null,
      "salesSplit": null,
      "stopStart": null,
      "stopEnd": null,
      "isPackage": null,
      "packSell": null,
      "packSellGM": null,
      "packSaleGM": 48.05,
      "transID": null
    },
    {
      "marginLine": 2093,
      "saleNo": "10348",
      "quantity": 1,
      "style": "TAX1",
      "vendor": "",
      "desc": "SALES TAX",
      "porD": "",
      "deptNo": "3",
      "vendorNo": "800",
      "commission": " ",
      "cost": 0,
      "itemFreight": 0,
      "sellPrice": 112.26,
      "salesman": "01",
      "status": "",
      "location": 0,
      "sellDate": "8/27/1999",
      "delDate": null,
      "rn": 0,
      "store": 1,
      "name": "CARTER",
      "shipDate": null,
      "gM": 0,
      "tele": "7402863125",
      "detail": null,
      "mailIndex": 302,
      "sS": null,
      "delPrint": null,
      "pullPrint": null,
      "commPd": null,
      "fldPosted": null,
      "spiff": null,
      "salesSplit": null,
      "stopStart": null,
      "stopEnd": null,
      "isPackage": null,
      "packSell": null,
      "packSellGM": null,
      "packSaleGM": 48.05,
      "transID": null
    },
    {
      "marginLine": 2094,
      "saleNo": "10348",
      "quantity": 0,
      "style": "SUB",
      "vendor": "",
      "desc": "Sub Total =",
      "porD": "",
      "deptNo": "3",
      "vendorNo": "800",
      "commission": " ",
      "cost": 0,
      "itemFreight": 0,
      "sellPrice": 1983.26,
      "salesman": "01",
      "status": "",
      "location": 0,
      "sellDate": "8/27/1999",
      "delDate": null,
      "rn": 0,
      "store": 1,
      "name": "CARTER",
      "shipDate": null,
      "gM": 0,
      "tele": "7402863125",
      "detail": null,
      "mailIndex": 302,
      "sS": null,
      "delPrint": null,
      "pullPrint": null,
      "commPd": null,
      "fldPosted": null,
      "spiff": null,
      "salesSplit": null,
      "stopStart": null,
      "stopEnd": null,
      "isPackage": null,
      "packSell": null,
      "packSellGM": null,
      "packSaleGM": 48.05,
      "transID": null
    },
    {
      "marginLine": 2095,
      "saleNo": "10348",
      "quantity": 3,
      "style": "PAYMENT",
      "vendor": "",
      "desc": "VISA CARD       08/27/1999",
      "porD": "",
      "deptNo": "3",
      "vendorNo": "800",
      "commission": " ",
      "cost": 0,
      "itemFreight": 0,
      "sellPrice": 283.26,
      "salesman": "01",
      "status": "",
      "location": 0,
      "sellDate": "8/27/1999",
      "delDate": null,
      "rn": 0,
      "store": 1,
      "name": "CARTER",
      "shipDate": null,
      "gM": 0,
      "tele": "7402863125",
      "detail": null,
      "mailIndex": 302,
      "sS": null,
      "delPrint": null,
      "pullPrint": null,
      "commPd": null,
      "fldPosted": null,
      "spiff": null,
      "salesSplit": null,
      "stopStart": null,
      "stopEnd": null,
      "isPackage": null,
      "packSell": null,
      "packSellGM": null,
      "packSaleGM": 48.05,
      "transID": null
    }
  ],
  "mail": {
    "index": 302,
    "last": "CARTER",
    "first": "JOHN",
    "address": "259 LOCUST ST",
    "addAddress": "",
    "city": "JACKSON, OH.",
    "zip": "45640",
    "tele": "7402863125",
    "tele2": "",
    "special": "",
    "type": "0",
    "custType": 2,
    "typeIndex": null,
    "email": "johncarter@comcast.com",
    "blank": "",
    "business": "False",
    "creditCard": 0,
    "expDate": "",
    "taxZone": 0,
    "phoneLabel1": null,
    "phoneLabel2": null
  }
}
"""
}
